### ISSUE TITLE
Post dates missing

### ISSUE THREAD

**Issue by russianlife** [JasPanesar/MuraConverter#4]
Post date from WordPress does not xfer into release date field for the Mura post.

Also, would be nice if the credit field could be filled in, based on contributor of WordPress post, if that info is attached in there.

**Comment by JasPanesar** [comment]
Post dates seem to be a little strange -- I'm pulling in a few of the other fields and will try to tackle this one after I get the SEO URLs working how I like.

**Comment by JasPanesar** [comment]
I have implemented post date importing in the pull request that Greg will be merging once he has a chance to look it over.

**Comment by gregmoser** [comment]
This has been resolved.
