### ISSUE TITLE
Blog location

### ISSUE THREAD

**Issue by russianlife** [JasPanesar/MuraConverter#5]
During import, should be able to specify location of posts in the Mura site's hierarchy tree, i.e. which page will be the parent of all imported pages. This just puts them all under home.

**Comment by JasPanesar** [comment]
I have implemented blog import location in my fork, I will be asking Greg to import.

**Comment by gregmoser** [comment]
I'm going to merge this in as soon as Jas & I can figure out what from the develop branch also needs to get merged in so that the app can be cleaned up with all the great features Jas has been adding.

**Comment by JasPanesar** [comment]
Greg, updated pull request is ready that should solve this problem.  The drop down list of locations isn't the prettiest (or indented) according to the hierarchy so I outputted the item type into the dropdown (page, folder, etc) to hopefully help pick the correct node easier.

**Comment by gregmoser** [comment]
This is resolved.
