### ISSUE TITLE
Imported ended with scary white screen

### ISSUE THREAD

**Issue by russianlife** [JasPanesar/MuraConverter#6]
Everything imported, but widget ended with white out screen rather than a task completed confirmation.

**Comment by JasPanesar** [comment]
I have been sorting something similar out for myself, if you have some screenshots I can look at it while it's fresh in my head.  I found in my case that PHP and wordpress was timing out and truncating the XML file causing me all sorts of problems.

**Comment by JasPanesar** [comment]
There is a screen that says "import complete" when the XML is imported successfully now.  Not sure if this is an old issue that should have been closed off.

**Comment by gregmoser** [comment]
Please re-open if this error persists.
